# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'dogbuddy' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for dogbuddy

  pod 'Google/SignIn'

  target 'dogbuddyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
